language: cpp

compiler:
    - gcc

env:
  global:
    # Encrypted personal access token
    - secure: EAh+5LSC4DlIqvXTrYJUAq8isa0Jfp/Ko5xAsVWJrkmAFfsQsaO4XRXG0U964LKROv0GHISDJtBCEkxnhBu5nRJ3dGkNd/pmElhUAiPK6qXPBEfrJAUQldCvFZ/7p8u6Jrn5r3/bFY3yos4hkn/EsFNYRb9Bj/NlqxisyyYUyag=
    # GitHub user name
    - GH_USR=CaioIcy
    # GitHub link
    - GH_REF=github.com/CaioIcy/sdl2-engine.git
    # Project name (no spaces)
    - T_NAME_PROJECT=sdl2-engine
    # This variable tells TravisCI to publish to gh-pages and Coveralls:
    - T_DO_PUBLISH_GH_COV=Yes
    # Valgrind run of the project will automatically close in a couple of seconds
    - T_DO_TIMED_RUN=ON

before_install:
    - ./utils/travis/before_install.sh

install:
    - ./utils/travis/install.sh

script: ./build.sh debug

after_success:
    - ./utils/travis/after_success.sh
