language: cpp

compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test # g++-4.8
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots # SDL2
  - sudo apt-get update -qq

install:
  - sudo apt-get install g++-4.8 doxygen libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - make

branches:
  only:
    - master

os: linux
